#[shell]
#program = "/bin/zsh"
#args = ["-l"]

[env]


[font]
size = 16.0
normal = { "family" = "Rec Mono Custom" }

[window]
opacity = 1
decorations = "Full"
padding = { x = 5, y = 0 }
blur = true
resize_increments = true


[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "0", mods = "Control|Shift", action = "ResetFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
]
