#[shell]
#program = "/bin/zsh"
#args = ["-l"]

[env]


[font]
size = 14.0
normal = { "family" = "JetBrainsMono Nerd Font" }

[window]
opacity = 0.8
decorations = "Full"
padding = { x = 5, y = 0 }
blur = true
resize_increments = true


[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
{ key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
{ key = "0", mods = "Control|Shift", action = "ResetFontSize" },
]
