#[shell]
#program = "/bin/zsh"
#args = ["-l"]

[env]


[font]
size = 14.0
normal = { family = "Rec Mono Custom3", style = "Regular" }

[window]
opacity = 0.9
blur = false
decorations = "Full" # Full None Transparent Buttonless
padding = { x = 5, y = 0 }
resize_increments = true


[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  #{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Enter", mods = "Alt|Shift", action = "ToggleFullScreen" },
  { key = "Enter", mods = "Alt", action = "ToggleMaximized" },
]
